# Site wide configuration
#Titel
title: Jekyll nieuws site
#beschrijving
description: Dit is een beschrijving
# De site logo; plaats in de /images/ map
logo: # 120x120 px default image used for Twitter summary card
# De default teaser die bij elk bericht verschijnt.
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale: nl
url: 

# Jekyll configuration12

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  
 

#Prose configuratie
prose:
	#rooturl: '_posts'
    siteurl: 'http://docs.simonwhiteley.nl'
    media: 'media'
    ignore:
    	- index.md
        - _config.yml
        - /_layouts
        - /_includes
        

# Site owner
owner:
  name: Simon R. Whiteley
  email: simonwhiteley@hotmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: "Simon writes stuff because he likes things"
  avatar: 6416139.jpeg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
